#!/usr/bin/env bash


prefix="package_rest_elasticsearch_$2"

if [[ "package_rest_elasticsearch_rest_elasticsearch_rest_elasticsearch_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_rest_elasticsearch_rest_elasticsearch_rest_elasticsearch_data_volume
	fi
	
